; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env]
; platform = teensy
; board = teensy41
; framework = arduino
; lib_deps = 
;     adafruit/Adafruit BMP3XX Library@^2.1.6
;     adafruit/Adafruit BNO055@^1.6.4
;     adafruit/Adafruit ICM20X@^2.0.7

[platformio]
default_envs = main

[env]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:main]
build_src_filter = 
	+<main.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:testingLeadLimit]
build_src_filter = 
	+<testingLeadLimit.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7
	
[env:testingLimitSwitches]
build_src_filter = 
	+<testingLimitSwitches.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:testingLandedState]
build_src_filter = 
	+<testingLandedState.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:testingOrientation]
build_src_filter = 
	+<testingOrientation.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7


[env:testingWaterAndSoil]
build_src_filter = 
	+<testingWaterAndSoil.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7


[env:testingSoilSensing]
build_src_filter = 
	+<testingSoilSensing.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:testingLeadScrew]
build_src_filter = 
	+<testingLeadScrew.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7
	
[env:testingWaterMotor]
build_src_filter = 
	+<testingWaterMotor.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:testingMotorAuger]
build_src_filter = 
	+<testingMotorAuger.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:testingLeadSlowDive]
build_src_filter = 
	+<testingLeadSlowDive.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:flightComputer329]
build_src_filter = 
	+<flightComputer329.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7



	
