; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env]
; platform = teensy
; board = teensy41
; framework = arduino
; lib_deps = 
;     adafruit/Adafruit BMP3XX Library@^2.1.6
;     adafruit/Adafruit BNO055@^1.6.4
;     adafruit/Adafruit ICM20X@^2.0.7

[platformio]
default_envs = main

[env]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:main]
build_src_filter = 
	+<main.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:testLeadLimit]
build_src_filter = 
	+<testLeadLimit.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7
	
[env:testLimitSwitches]
build_src_filter = 
	+<testLimitSwitches.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7
	


[env:landedState]
build_src_filter = 
	+<landedState.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7


[env:orientationTest]
build_src_filter = 
	+<orientationTest.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7


[env:waterPumpAndSoilDataTesting]
build_src_filter = 
	+<waterPumpAndSoilDataTesting.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7
	

[env:testEnv]
build_src_filter = 
	+<testEnv.cpp>
	+<Constants.hpp>
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7


	
