; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:main]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:testLeadLimit]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:testLimitSwitches]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7


[env:landedState]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7

[env:testEnv]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
	adafruit/Adafruit BMP3XX Library@^2.1.6
	adafruit/Adafruit BNO055@^1.6.4
	adafruit/Adafruit ICM20X@^2.0.7
